services:
    cto.CTOClient.doctrine.subscriber.fullName:
        class: CTO\AppBundle\EventListener\DoctrineCTOClientSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    cto.twigExtension.monthTranslate:
        class: CTO\AppBundle\TwigExtension\AppExtension
        public: false
        arguments: [@doctrine.orm.entity_manager, %aws_s3_base_url%]
        tags:
            - { name: twig.extension }

    cto.aws.s3:
        class: CTO\AppBundle\AWS\S3
        arguments: [%aws_s3_key%, %aws_s3_secret%, %aws_s3_bucket%, %aws_s3_region%, %aws_s3_base_url%]

    cto.sms.sender:
        class: CTO\AppBundle\Notification\SMSSender
        arguments:
            - @doctrine.orm.entity_manager
            - @mcfedr_resque.manager
            - %queue_name%
            - %alfa_sms_name%
            - %alfa_sms_ID%
            - %alfa_sms_password%
            - %alfa_sms_api_key%