<?php

namespace CTO\AppBundle\Entity\Repository;

use CTO\AppBundle\Entity\Notification;
use Doctrine\ORM\EntityRepository;

/**
 * NotificationReportRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class NotificationReportRepository extends EntityRepository
{
    /**
     * @param Notification $notification
     * @return array
     */
    public function findBySomeNotification(Notification $notification)
    {
        return $this->createQueryBuilder("r")
            ->select("r, cl")
            ->join("r.client", "cl")
            ->where("r.notification = :notification")->setParameter("notification", $notification)
            ->orderBy("r.createdAt", "DESC")
            ->getQuery()
            ->getResult();
    }
}
